# test:
#   path: /test/{age<\d+>?0}
#   controller: App\Controller\TestController::test
#   methods: [GET, POST]
#   #host: localhost # il faut le change au moment de deploiyement
#   schemes: [https, http]
#   # defaults: 
#   #   age: 0
#   # requirements:
#   #   age: \d+